# https://docs.github.com/en/actions

name: Warp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: warp / cloudflare
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          secrets: |
            API_KEY
        env:
          API_KEY: ${{ secrets.API_KEY }}